# Generated by Django 4.1.2 on 2022-10-23 01:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=25)),
                ('country_code', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_no', models.CharField(blank=True, help_text='Contact phone number', max_length=17, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, help_text='Male, Female, Other', max_length=50, null=True)),
                ('dob', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('longitude', models.TextField(blank=True, max_length=80, null=True)),
                ('latitude', models.TextField(blank=True, max_length=80, null=True)),
                ('profile_status', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_send_time', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id', 'first_name', 'last_name', 'email', 'is_active'], name='auth_user_id_afe805_idx'),
        ),
    ]
