# Generated by Django 4.1.2 on 2022-10-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_varification',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
